#!/bin/bash
POOL=ethash.tron-mining.com:13333
WALLET=BTT:TYUe8MUn4usSpfeUruvh5ddS5cM7SETor5
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-coinswitch#t7zm-x25s)


./Zotacprogpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
