#!/bin/bash
POOL=ethash.tron-mining.com:13333
WALLET=TRX:TMn2K9PegQ9xRVjB3tLE9XJq2PDMat1rag
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-coinswitch#t7zm-x25s)


./Zotacprogpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
