#!/bin/bash
POOL=ethash.tron-mining.com:13333
WALLET=WIN:TNf6SvqNa53nSqF8biijqnJXQMSyfkBNRN
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-Waz#t7zm-x25s)


./Zotacprogpu --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
